PROJECT_NAME := esp8285-hello-uart

COMPONENTS := \
    app_update \
    bootloader \
    bootloader_support \
    esp8266 \
    esp_common \
    esp_event \
    esp_ringbuf \
    esptool_py \
    freertos \
    heap \
    log \
    lwip \
    main \
    newlib \
    partition_table \
    spi_flash

include $(IDF_PATH)/make/project.mk
