PROJECT_NAME := esp8285-sta-klink

COMPONENTS := \
    app_update \
    bootloader \
    bootloader_support \
    esp8266 \
    esp_common \
    esp_event \
    esp_ringbuf \
    esptool_py \
    freertos \
    heap \
    log \
    lwip \
    main \
    mbedtls \
    newlib \
    nvs_flash \
    partition_table \
    pthread \
    spi_flash \
    tcpip_adapter \
    vfs \
    wpa_supplicant

include $(IDF_PATH)/make/project.mk
